---
title: "Uma senhora toma chá"
output:
  html_document:
    toc: false
---

```{r setup, message=FALSE}
options(width=25)
source("setup_knitr.R")
```

# Objetivo:

Seminários onde cada dupla de alunos apresenta um dos capítulos do livro:

- Salsburg, D.
  [Uma senhora toma chá. Como a estatística revolucionou a ciência no século XX](http://www.zahar.com.br/livro/uma-senhora-toma-cha).
  Rio de Janeiro: Zahar, 2009.

Apresentações sucintas de no máximo 10 minutos

# Organização dos seminários

- **Tamanho de cada capítulo:** 

```{r pags, echo=TRUE}
pgs <- c(17, 24, 36, 43, 49, 58, 64, 73, 80, 89, 99, 
         107, 113, 121, 131, 137, 144, 153, 164, 173, 
         181, 189, 195, 203, 210, 218, 223, 231, 237)
(len <- diff(c(pgs, 250))) ### tamanhos
```

- **Capítulos selecionados:**
```{r caps, echo=TRUE}
(caps <- c(2:(length(len)-1))[len[-c(1,29)]>6])
```


- **Atribuição dos capítulos às duplas**
```{r tabela, echo=TRUE}
cap.g <- c(21, 2, 7, 14, 5, 27, 13, 20, 10, 11, 3, 17, 25, 19, 8, 9, 18, 24, 16, 23)

o.gr <- order(cap.g)
kable(matrix(paste0('Cap', caps, ' -> Dup', o.gr),
             ncol=5, byrow=TRUE,
             dimnames=list(paste0(7*(1:4),'/11'), 1:5)))
```

```
Dupla 1 : 20160206 20160211 
Dupla 2 : 20160237 20160210 
Dupla 3 : 20160234 20160235 
Dupla 4 : 20160226 20165728 
Dupla 5 : 20160203 LUAN 
Dupla 6 : 20160220 20160212 
Dupla 7 : 20160214 20160231 
Dupla 8 : 20160204 20160233 
Dupla 9 : 20160205 20160227 
Dupla 10 : 20160213 20160208 
Dupla 11 : 20160242 20160225 
Dupla 12 : 20165740 20160194 
Dupla 13 : 20160239 20160215 
Dupla 14 : 20160218 20160228 
Dupla 15 : 20160230 20160216 
Dupla 16 : 20160221 20160217 
Dupla 17 : 20160240 20160238 
Dupla 18 : 20160229
```

<!-- links -->

[Elias T. Krainski]: https://eliaskrainski.github.io
[LEG]: http://www.leg.ufpr.br
[Resolução 49/15 - CEPE]: http://www.ufpr.br/soc/descarregar_arquivo.php?cod=1064
